### ISSUE TITLE
Try this program on stereo-matching based depths

### ISSUE THREAD

**Issue by tangeroo** [OneEyedEagle/EAGLE-TextureMapping#2]
Hi, 
  Thanks for your excellent recurrence. I wanna try this program on stereo-matching based depths. But I don't know the following parameters means. Following in first line red marked, does it mean this is a relative pose between camera 0 and camera 1? Are next 2-5 lines quaternion matrix or some other format parameters. And furthermore, do you have any suggestions that what I should care if I use this program on stereo-matching based depths, maybe it's not easy to get a enough good result on stereo-matching based depths and I should do some filtering on depth maps? I'm new in this field, please don't mind for any bad requests and questions.
![image](https://user-images.githubusercontent.com/25971461/93598013-9ecd2a80-f9ee-11ea-8522-f2a117013efa.png)
  Thank you very much.

**Comment by OneEyedEagle** [comment]
The traj.txt is in the format from Qianyi Zhou's dataset.

For every 5 lines:

id id id+1   => the first line shows which image the following matrix is from. The plus one may be a mistake.

RT(0,0) RT(0,1) ... RT(0,3)
 ............................................
RT(3,0) RT(3,1) ... RT(3,3) 

  => the second to fifth lines store the matrix that transform the camera from world center to its position on the (id)th image, or from its position to the world center

I'm sorry that I don't know much about stereo-matching, as I focus on texture mapping or fixing.

**Comment by tangeroo** [comment]
thanks for your guidance，I understand. In addition, compared to the eccv 2014 paper "let there be color..."，does this method is good for outdoor scene too?
thank you.

**Comment by OneEyedEagle** [comment]
I don't think this method would work for large scenes, as it needs to iterate all frames, which may be affected by many factors.

The object larger, the iteration more difficult to get stable.

**Comment by tangeroo** [comment]
Thank you.
In your reply, you said larger object makes the iteration harder to get stable. Does high resolution make this too? Further more, I have read paper, but have some other questions.
(1)I don't know how the vote process works, is it  a face on 3D model projected to different images, then 7x7 regions around these projections are searched, or just take 7x7 region one time on one image and project it to other corresponding images to search? 
(2)Can illumination changes influence this method？When the illumination changes as follows, is it possible to keep stable iteration.
![image](https://user-images.githubusercontent.com/25971461/93880087-76f00680-fd0f-11ea-9405-58afb04cf056.png)
![Uploading image.png…]()
(3)Is it enough to detect some occlusions and avoid their use in weighting textures by the coherent measurement in E1 function? As in eccv 2014 they detect occlusions before view selections.
Too many questions and hope you don't mind.
Thank you.

**Comment by OneEyedEagle** [comment]
Larger object needs more views, which makes the iteration harder to make all frames be same or consistent.

1. The vote works when finding corresponding patchs between the source image and the target image. 
The method's key is that as Ms (texture images) are the average of all Ts (target images), it's possible to adjust Ts to make this average more accurate ( or less fuzzy).

In init, Ts are the same as Ss (sources), but after the first iteration, Ts are alse affected by the average results (Ms). So Ts may get a little fuzzy.

Then, the iteration will do a voting on S and T. For a patch on T, which is somewhat fuzzy affected by the Ms, the voting finds a most similar patch on S. To be equal, for a patch on S, the iteration will also find a patch on T that is most similar.

For a pixel on T, we get patchs including it on T, and we mark these patchs' corresponding patchs on S as the "similarity" term. We also get some patchs on S whose corresponding patchs on T include this pixel, and we mark these patchs on S as "coherent" term. We weight all RGBs from patchs and RGBs from Ms on the pixel to get a new pixel.

Lastly, all pixels on T will be replaced by a new pixel. And a new M will also be generated from all new Ts.

So you see, the obj and the cam-trajs only provide the projections between views. The intrinsic method is images' wrapping.

2. In my implementation, as I use RGB format to do the voting, the illumination do affect the results, especially for shadows. I prefer to think the method only fits in small objects' texture optimization, as results in the paper are all small items. The grassland in Chapter 6.2 is also a small region.

3. As the obj only provides the reprojection from a view to another view, if occlusions exist, the reprojection will be skipped, or errors occur. While the paper says nothing about the detail on reprojections, I implement the paper in a much more general way: 

first, do the ray-intersection to generate a depth for each view based on the ply; 

second, do the reprojection from a view to all other views, if the new depth get by projecting pixel from Image A to Image B is bigger than the depth on Depth B (we generated on the first step), then occlusion exists, and the projection fails, no process will be done later;

third, do iterations, which generate new Ts as 1. says.

**Comment by tangeroo** [comment]
Thanks for your patience and detailed explanations, reallyyy helpful. I think I have no more questions.
Best Wishes!

**Comment by tangeroo** [comment]
Thanks for your patience and detailed explanations, reallyyy helpful. I think I have no more questions.
Best Wishes!

**Comment by YuzhiChen001** [comment]
> 



> The traj.txt is in the format from Qianyi Zhou's dataset.
> 
> For every 5 lines:
> 
> id id id+1 => the first line shows which image the following matrix is from. The plus one may be a mistake.
> 
> RT(0,0) RT(0,1) ... RT(0,3) ............................................ RT(3,0) RT(3,1) ... RT(3,3)
> 
> => the second to fifth lines store the matrix that transform the camera from world center to its position on the (id)th image, or from its position to the world center
> 
> I'm sorry that I don't know much about stereo-matching, as I focus on texture mapping or fixing.

![image](https://user-images.githubusercontent.com/116945973/218654882-e1a19a25-5070-43b6-85cf-e1fe7130a813.png)


> The traj.txt is in the format from Qianyi Zhou's dataset.
> 
> For every 5 lines:
> 
> id id id+1 => the first line shows which image the following matrix is from. The plus one may be a mistake.
> 
> RT(0,0) RT(0,1) ... RT(0,3) ............................................ RT(3,0) RT(3,1) ... RT(3,3)
> 
> => the second to fifth lines store the matrix that transform the camera from world center to its position on the (id)th image, or from its position to the world center
> 
> I'm sorry that I don't know much about stereo-matching, as I focus on texture mapping or fixing.

Hello,in Reality Capture,i set the calibration.xml like this.
$ExportCameras( 
$(index:d) $(index:d) $(index+1:d)
$(R00:g)	$(R01:g)	$(R02:g)	$(tx:g)
$(R10:g)	$(R11:g)	$(R12:g)	$(ty:g)
$(R20:g)	$(R21:g)	$(R22:g)	$(tz:g)
0                 0                   0                  1			
)
is that right？Looking forward to hearing from you.

**Comment by icedCoffe001** [comment]
> The traj.txt is in the format from Qianyi Zhou's dataset.
> 
> For every 5 lines:
> 
> id id id+1 => the first line shows which image the following matrix is from. The plus one may be a mistake.
> 
> RT(0,0) RT(0,1) ... RT(0,3) ............................................ RT(3,0) RT(3,1) ... RT(3,3)
> 
> => the second to fifth lines store the matrix that transform the camera from world center to its position on the (id)th image, or from its position to the world center
> 
> I'm sorry that I don't know much about stereo-matching, as I focus on texture mapping or fixing.

Hello,in Reality Capture,i set the calibration.xml like this.
$ExportCameras(
$(index:d) $(index:d) $(index+1:d)
$(R00:g)	$(R01:g)	$(R02:g)	$(tx:g)
$(R10:g)	$(R11:g)	$(R12:g)	$(ty:g)
$(R20:g)	$(R21:g)	$(R22:g)	$(tz:g)
0                 0                   0                  1			
)
is that right？Looking forward to hearing from you.

**Comment by OneEyedEagle** [comment]
I'm not sure if the matrix is right, as I have graduated for 2 years.

The matrix means 
_transform the camera from world center (0,0,0) to the camera position of the (id)th image_

If the results don't fix with others, try to apply a transposition to the RT matrix?


> I'm sorry that I don't know much about stereo-matching, as I focus on texture mapping or fixing.
> 
> Hello,in Reality Capture,i set the calibration.xml like this. $ExportCameras( (index:d)(index:d) $(index+1:d) (R00:g)(R01:g) (R02:g)(tx:g) (R10:g)(R11:g) (R12:g)(ty:g) (R20:g)(R21:g) (R22:g)(tz:g) 0 0 0 1 ) is that right？Looking forward to hearing from you.
